atest.cpp
void test1(std::fstream &partsFile, char partsfilename[52])
Test the if the parts file could be opened.
Referenced by main.
bool test2(Inventory &inventory)
Test whether the heterogenous collection contains the derived classes.
Referenced by main, test3.
bool test3(String test1, String test2)
Test the non case sensitive String compare.
References test2.
Referenced by main.
bool test4(String asd, const char *test)
Test the string shortener.
Referenced by main.