Part
String Part::brand
Referenced by get_brand, Part, print, CPU::print.
String Part::type
Gyártó
Referenced by get_type, print.
int Part::price
Típus.
Referenced by get_price, print.
Part::Part(String brand="", String type="", int price=0)
Ár.
References brand.
virtual Part::~Part()
String Part::get_brand()
References brand.
String Part::get_type()
References type.
int Part::get_price()
References price.
void Part::print(std::ostream &os) const
References brand, price, type.
Referenced by operator<<, CPU::print, GPU::print, MOBO::print, RAM::print, Case::print, PSU::print, Storage::print.