String
char* String::pData
Referenced by c_str, operator+, operator--, operator=, operator==, operator[], String, ~String.
size_t String::len
pointer az adatra
Referenced by length, operator+, operator--, operator=, operator==, operator[], size, String.
size_t String::size() const
hossz lezáró nulla nélkül
Visszaadja a string hosszát
References len.
Referenced by CompatibilityList::addItems, CompatibilityList::CompatibilityList.
size_t String::length() const
Visszaadja a string hosszát.
References len.
Referenced by LoadParams, operator==.
String::String()
Default konstruktor.
Referenced by operator+.
String::String(char ch)
Konstruktor: egy char karakterre.
References len, pData.
String::String(const char *p)
Konstruktor: egy karakter tömbre.
References len, pData.
String::String(const String &s1)
Konstruktor: egy másik Stringre.
References len, pData.
const char* String::c_str() const
C-stringet ad vissza.
References pData.
Referenced by operator<<, operator==.
String::~String()
Destruktor.
References pData.
String & String::operator=(const String &rhs_s)
Egyenlőség operator.
References len, pData.
String& String::operator+=(const String &rhs_s)
Pluszegyenlő operator.
String String::operator+(const String &rhs_s) const
string + string
References len, pData.
String String::operator+(char rhs_c)
string + karakter
References String.
bool String::operator==(String &rhs_s)
hasonlító operator stringgel
References c_str, len, length, pData, stolower.
bool String::operator==(const char *rhs_s)
hasonlító operator char tömbbel
References len, pData, stolower.
bool String::operator==(const char *rhs_s) const
References len, pData, stolower.
String String::operator--(int a)
kitörli az utolsó karaktert a stringből
References len, pData.
char & String::operator[](unsigned int idx)
index operator
References len, pData.
const char & String::operator[](unsigned int idx) const
index operator
References len, pData.
void String::erase()
törli a stringben lévő karaktereket