.TH "C:/Users/cxl20/Documents/Visual Studio 2017/Prog2HF/Prog2HF/atest.cpp" 3 "Fri May 3 2019" "Prog2HF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/cxl20/Documents/Visual Studio 2017/Prog2HF/Prog2HF/atest.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'atest\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBtest1\fP (std::fstream &partsFile, const char filename[52])"
.br
.RI "Test the if the parts file could be opened\&. "
.ti -1c
.RI "bool \fBtest2\fP (\fBInventory\fP &inventory)"
.br
.RI "Test whether the heterogenous collection contains the derived classes\&. "
.ti -1c
.RI "bool \fBtest3\fP (\fBString\fP \fBtest1\fP, \fBString\fP \fBtest2\fP)"
.br
.RI "Test the non case sensitive \fBString\fP compare\&. "
.ti -1c
.RI "bool \fBtest4\fP (\fBString\fP asd, const char *test)"
.br
.RI "Test the string shortener\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "void test1 (std::fstream & partsFile, const char filename[52])"

.PP
Test the if the parts file could be opened\&. 
.SS "bool test2 (\fBInventory\fP & inventory)"

.PP
Test whether the heterogenous collection contains the derived classes\&. 
.SS "bool test3 (\fBString\fP test1, \fBString\fP test2)"

.PP
Test the non case sensitive \fBString\fP compare\&. 
.SS "bool test4 (\fBString\fP asd, const char * test)"

.PP
Test the string shortener\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for Prog2HF from the source code\&.
