.TH "Build" 3 "Thu May 2 2019" "Prog2HF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Build
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Builds\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBuild\fP (size_t capacity=7)"
.br
.ti -1c
.RI "\fB~Build\fP ()"
.br
.ti -1c
.RI "template<typename T > void \fBpush_back\fP (T *part)"
.br
.ti -1c
.RI "const \fBPart\fP * \fBoperator[]\fP (int idx) const"
.br
.ti -1c
.RI "\fBPart\fP * \fBoperator[]\fP (int idx)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Build::Build (size_t capacity = \fC7\fP)\fC [inline]\fP"

.SS "Build::~Build ()\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "const \fBPart\fP* Build::operator[] (int idx) const\fC [inline]\fP"

.SS "\fBPart\fP* Build::operator[] (int idx)\fC [inline]\fP"

.SS "template<typename T > void Build::push_back (T * part)"


.SH "Author"
.PP 
Generated automatically by Doxygen for Prog2HF from the source code\&.
