.TH "C:/Users/cxl20/Documents/Visual Studio 2017/Prog2HF/Prog2HF Directory Reference" 3 "Fri May 3 2019" "Prog2HF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/cxl20/Documents/Visual Studio 2017/Prog2HF/Prog2HF Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBatest\&.cpp\fP"
.br
.ti -1c
.RI "file \fBatest\&.h\fP"
.br
.ti -1c
.RI "file \fBBuilds\&.cpp\fP"
.br
.ti -1c
.RI "file \fBBuilds\&.h\fP"
.br
.ti -1c
.RI "file \fBCompatibility\&.cpp\fP"
.br
.ti -1c
.RI "file \fBCompatibility\&.h\fP"
.br
.ti -1c
.RI "file \fBInventory\&.cpp\fP"
.br
.ti -1c
.RI "file \fBInventory\&.h\fP"
.br
.ti -1c
.RI "file \fBmain\&.cpp\fP"
.br
.ti -1c
.RI "file \fBmain\&.h\fP"
.br
.ti -1c
.RI "file \fBParts\&.cpp\fP"
.br
.ti -1c
.RI "file \fBParts\&.h\fP"
.br
.ti -1c
.RI "file \fBschtring\&.cpp\fP"
.br
.ti -1c
.RI "file \fBschtring\&.hpp\fP"
.br
.ti -1c
.RI "file \fBSFML_test\&.cpp\fP"
.br
.in -1c
