.TH "C:/Users/cxl20/Documents/Visual Studio 2017/Prog2HF/Prog2HF/Compatibility.cpp" 3 "Thu May 2 2019" "Prog2HF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/cxl20/Documents/Visual Studio 2017/Prog2HF/Prog2HF/Compatibility.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'Compatibility\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (std::ostream &os, const \fBCompatibilityList\fP &cl)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "std::ostream& operator<< (std::ostream & os, const \fBCompatibilityList\fP & cl)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Prog2HF from the source code\&.
