.TH "C:/Users/cxl20/Documents/Visual Studio 2017/Prog2HF/Prog2HF/Compatibility.h" 3 "Fri May 3 2019" "Prog2HF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/cxl20/Documents/Visual Studio 2017/Prog2HF/Prog2HF/Compatibility.h
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include 'schtring\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCompatibilityList\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (std::ostream &os, const \fBCompatibilityList\fP &cl)"
.br
.ti -1c
.RI "template<typename T1  = String, typename T2  = String> bool \fBcompatible\fP (T1 is, T2 with, \fBCompatibilityList\fP cl)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "template<typename T1  = String, typename T2  = String> bool compatible (T1 is, T2 with, \fBCompatibilityList\fP cl)"

.SS "std::ostream& operator<< (std::ostream & os, const \fBCompatibilityList\fP & cl)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Prog2HF from the source code\&.
