.TH "CompatibilityList" 3 "Thu May 2 2019" "Prog2HF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CompatibilityList
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Compatibility\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCompatibilityList\fP ()"
.br
.ti -1c
.RI "\fBCompatibilityList\fP (\fBString\fP &)"
.br
.ti -1c
.RI "\fB~CompatibilityList\fP ()"
.br
.ti -1c
.RI "int \fBget_length\fP () const"
.br
.ti -1c
.RI "\fBString\fP * \fBget_listp\fP () const"
.br
.ti -1c
.RI "void \fBaddItems\fP (\fBString\fP &)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (\fBString\fP &rhs)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const char *rhs)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CompatibilityList::CompatibilityList ()\fC [inline]\fP, \fC [explicit]\fP"

.SS "CompatibilityList::CompatibilityList (\fBString\fP & slist)\fC [explicit]\fP"

.SS "CompatibilityList::~CompatibilityList ()\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void CompatibilityList::addItems (\fBString\fP & slist)"

.SS "int CompatibilityList::get_length () const\fC [inline]\fP"

.SS "\fBString\fP* CompatibilityList::get_listp () const\fC [inline]\fP"

.SS "bool CompatibilityList::operator== (\fBString\fP & rhs)\fC [inline]\fP"

.SS "bool CompatibilityList::operator== (const char * rhs)\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Prog2HF from the source code\&.
