.TH "CPU" 3 "Thu May 2 2019" "Prog2HF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CPU \- Processzor\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Parts\&.h>\fP
.PP
Inherits \fBPart\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCPU\fP (\fBString\fP \fBbrand\fP, \fBString\fP \fBtype\fP, int \fBprice\fP, int clk, int cores, \fBString\fP socket, bool multithreading)"
.br
.ti -1c
.RI "\fBCPU\fP (\fBTempInput\fP &tmp)"
.br
.ti -1c
.RI "void \fBprint\fP (std::ostream &os) const"
.br
.ti -1c
.RI "void \fBprint\fP (\fButos_ostream\fP &tos) const"
.br
.ti -1c
.RI "void \fBtesth\fP () const"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Processzor\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CPU::CPU (\fBString\fP brand, \fBString\fP type, int price, int clk, int cores, \fBString\fP socket, bool multithreading)\fC [inline]\fP, \fC [explicit]\fP"

.SS "CPU::CPU (\fBTempInput\fP & tmp)\fC [inline]\fP, \fC [explicit]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void CPU::print (std::ostream & os) const\fC [virtual]\fP"

.PP
Reimplemented from \fBPart\fP\&.
.SS "void CPU::print (\fButos_ostream\fP & tos) const\fC [virtual]\fP"

.PP
Reimplemented from \fBPart\fP\&.
.SS "void CPU::testh () const"


.SH "Author"
.PP 
Generated automatically by Doxygen for Prog2HF from the source code\&.
