.TH "HDD" 3 "Wed Apr 3 2019" "Prog2HF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HDD
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Parts\&.h>\fP
.PP
Inherits \fBStorage\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHDD\fP (\fBString\fP \fBbrand\fP, \fBString\fP \fBtype\fP, int \fBprice\fP, int \fBsize\fP, int \fBreadspeed\fP, int \fBwritespeed\fP, int rpm)"
.br
.RI "Fordulatszám\&. "
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "HDD::HDD (\fBString\fP brand, \fBString\fP type, int price, int size, int readspeed, int writespeed, int rpm)\fC [inline]\fP, \fC [explicit]\fP"

.PP
Fordulatszám\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Prog2HF from the source code\&.
