.TH "C:/Users/cxl20/Documents/Visual Studio 2017/Prog2HF/Prog2HF/Inventory.cpp" 3 "Fri May 3 2019" "Prog2HF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/cxl20/Documents/Visual Studio 2017/Prog2HF/Prog2HF/Inventory.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'Inventory\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBsetEnum\fP (\fBString\fP inst, enum \fBenumPart\fP &e)"
.br
.ti -1c
.RI "void \fBLoadParams\fP (std::istream &is, \fBTempInput\fP &tmp, int const params)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void LoadParams (std::istream & is, \fBTempInput\fP & tmp, int const params)"

.SS "void setEnum (\fBString\fP inst, enum \fBenumPart\fP & e)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Prog2HF from the source code\&.
