.TH "C:/Users/cxl20/Documents/Visual Studio 2017/Prog2HF/Prog2HF/main.cpp" 3 "Fri May 3 2019" "Prog2HF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/cxl20/Documents/Visual Studio 2017/Prog2HF/Prog2HF/main.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'main\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.ti -1c
.RI "void \fBprintMain\fP ()"
.br
.ti -1c
.RI "void \fBprintPartsList\fP (\fBInventory\fP &inventory)"
.br
.ti -1c
.RI "void \fBaddPartHelper\fP (\fBInventory\fP &inventory, \fBTempInput\fP &tmp)"
.br
.ti -1c
.RI "int \fBremovePartHelper\fP (\fBInventory\fP &inventory, enum \fBenumMenu\fP &eM)"
.br
.ti -1c
.RI "void \fBsaveInventory\fP (std::fstream &tempFile, std::fstream &origFile, \fBInventory\fP &inventory, std::streampos &pos, const char *partsfilename)"
.br
.ti -1c
.RI "void \fBanimate\fP (char c)"
.br
.ti -1c
.RI "int \fBevaluateInput\fP (\fBInventory\fP &inventory)"
.br
.ti -1c
.RI "void \fBevaluateCommand\fP (enum \fBenumMenu\fP &eM)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void addPartHelper (\fBInventory\fP & inventory, \fBTempInput\fP & tmp)"

.SS "void animate (char c)"

.SS "void evaluateCommand (enum \fBenumMenu\fP & eM)"

.SS "int evaluateInput (\fBInventory\fP & inventory)"

.SS "int main (int argc, char ** argv)"
Alapértelmezett parts fájl név
.PP
Parts fájl nevének beállítása indítási parancsból
.PP
első 5 sor átmásolása
.PP
pozíció mentése kiíráshoz 
.SS "void printMain ()"

.SS "void printPartsList (\fBInventory\fP & inventory)"

.SS "int removePartHelper (\fBInventory\fP & inventory, enum \fBenumMenu\fP & eM)"

.SS "void saveInventory (std::fstream & tempFile, std::fstream & origFile, \fBInventory\fP & inventory, std::streampos & pos, const char * partsfilename)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Prog2HF from the source code\&.
