.TH "C:/Users/cxl20/Documents/Visual Studio 2017/Prog2HF/Prog2HF/main.h" 3 "Fri May 3 2019" "Prog2HF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/cxl20/Documents/Visual Studio 2017/Prog2HF/Prog2HF/main.h
.SH SYNOPSIS
.br
.PP
\fC#include <chrono>\fP
.br
\fC#include <thread>\fP
.br
\fC#include 'schtring\&.hpp'\fP
.br
\fC#include <cstdio>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <limits>\fP
.br
\fC#include 'Parts\&.h'\fP
.br
\fC#include 'Inventory\&.h'\fP
.br
\fC#include 'atest\&.h'\fP
.br
\fC#include 'Builds\&.h'\fP
.br

.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBenumMenu\fP { \fBeMain\fP = 1, \fBePartsList\fP = 11, \fBePartsAdd\fP = 12, \fBePartsRemove\fP = 13, \fBeBuildsList\fP = 21, \fBeBuildsAdd\fP = 22, \fBeExit\fP = 9 }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.ti -1c
.RI "void \fBsaveInventory\fP (std::fstream &, std::fstream &, \fBInventory\fP &, std::streampos &, const char *)"
.br
.ti -1c
.RI "void \fBanimate\fP (char)"
.br
.ti -1c
.RI "void \fBprintMain\fP ()"
.br
.ti -1c
.RI "void \fBevaluateCommand\fP (enum \fBenumMenu\fP &)"
.br
.ti -1c
.RI "void \fBprintPartsList\fP (\fBInventory\fP &)"
.br
.ti -1c
.RI "void \fBaddPartHelper\fP (\fBInventory\fP &, \fBTempInput\fP &)"
.br
.ti -1c
.RI "int \fBremovePartHelper\fP (\fBInventory\fP &, \fBenumMenu\fP &)"
.br
.ti -1c
.RI "int \fBevaluateInput\fP (\fBInventory\fP &)"
.br
.ti -1c
.RI "void \fBsaveParts\fP (const \fBInventory\fP &)"
.br
.ti -1c
.RI "void \fBsaveOrders\fP (const \fBOrders\fP &)"
.br
.ti -1c
.RI "std::fstream & \fBGotoLine\fP (std::fstream &file, unsigned int n)"
.br
.RI "n edik sorra ugrik egy file streamben "
.ti -1c
.RI "void \fBclearcmd\fP ()"
.br
.RI "kitörli a terminált "
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBenumMenu\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIeMain \fP\fP
.TP
\fB\fIePartsList \fP\fP
.TP
\fB\fIePartsAdd \fP\fP
.TP
\fB\fIePartsRemove \fP\fP
.TP
\fB\fIeBuildsList \fP\fP
.TP
\fB\fIeBuildsAdd \fP\fP
.TP
\fB\fIeExit \fP\fP
.SH "Function Documentation"
.PP 
.SS "void addPartHelper (\fBInventory\fP &, \fBTempInput\fP &)"

.SS "void animate (char)"

.SS "void clearcmd ()\fC [inline]\fP"

.PP
kitörli a terminált 
.SS "void evaluateCommand (enum \fBenumMenu\fP &)"

.SS "int evaluateInput (\fBInventory\fP &)"

.SS "std::fstream& GotoLine (std::fstream & file, unsigned int n)\fC [inline]\fP"

.PP
n edik sorra ugrik egy file streamben 
.SS "int main (int argc, char ** argv)"
Alapértelmezett parts fájl név
.PP
Parts fájl nevének beállítása indítási parancsból
.PP
első 5 sor átmásolása
.PP
pozíció mentése kiíráshoz 
.SS "void printMain ()"

.SS "void printPartsList (\fBInventory\fP &)"

.SS "int removePartHelper (\fBInventory\fP &, \fBenumMenu\fP &)"

.SS "void saveInventory (std::fstream &, std::fstream &, \fBInventory\fP &, std::streampos &, const char *)"

.SS "void saveOrders (const \fBOrders\fP &)"

.SS "void saveParts (const \fBInventory\fP &)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Prog2HF from the source code\&.
