.TH "C:/Users/cxl20/Documents/Visual Studio 2017/Prog2HF/Prog2HF/memtrace.cpp" 3 "Wed Apr 3 2019" "Prog2HF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/cxl20/Documents/Visual Studio 2017/Prog2HF/Prog2HF/memtrace.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <time\&.h>\fP
.br
\fC#include <ctype\&.h>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Prog2HF from the source code\&.
