.TH "MOBO" 3 "Wed Apr 3 2019" "Prog2HF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MOBO
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Parts\&.h>\fP
.PP
Inherits \fBPart\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMOBO\fP (\fBString\fP \fBbrand\fP, \fBString\fP \fBtype\fP, int \fBprice\fP, \fBString\fP socket, \fBString\fP chipset, \fBString\fP formfactor)"
.br
.RI "Méret szabvány\&. "
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "MOBO::MOBO (\fBString\fP brand, \fBString\fP type, int price, \fBString\fP socket, \fBString\fP chipset, \fBString\fP formfactor)\fC [inline]\fP, \fC [explicit]\fP"

.PP
Méret szabvány\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Prog2HF from the source code\&.
