.TH "Orders" 3 "Thu May 2 2019" "Prog2HF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Orders
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Builds\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBOrders\fP (size_t capacity=1)"
.br
.ti -1c
.RI "\fB~Orders\fP ()"
.br
.ti -1c
.RI "template<typename T > void \fBpush_back\fP (T *part)"
.br
.ti -1c
.RI "const \fBBuild\fP \fBoperator[]\fP (int idx) const"
.br
.ti -1c
.RI "\fBBuild\fP \fBoperator[]\fP (int idx)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Orders::Orders (size_t capacity = \fC1\fP)\fC [inline]\fP"

.SS "Orders::~Orders ()\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "const \fBBuild\fP Orders::operator[] (int idx) const\fC [inline]\fP"

.SS "\fBBuild\fP Orders::operator[] (int idx)\fC [inline]\fP"

.SS "template<typename T > void Orders::push_back (T * part)"


.SH "Author"
.PP 
Generated automatically by Doxygen for Prog2HF from the source code\&.
