.TH "C:/Users/cxl20/Documents/Visual Studio 2017/Prog2HF/Prog2HF/Parts.h" 3 "Fri May 3 2019" "Prog2HF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/cxl20/Documents/Visual Studio 2017/Prog2HF/Prog2HF/Parts.h
.SH SYNOPSIS
.br
.PP
\fC#include 'schtring\&.hpp'\fP
.br
\fC#include <typeinfo>\fP
.br
\fC#include <cctype>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBTempInput\fP"
.br
.RI "Lehetséges inputokat tárolja adatokkal való konstruáláshoz\&. "
.ti -1c
.RI "class \fBPart\fP"
.br
.RI "Alap alkatrész típus\&. "
.ti -1c
.RI "class \fBCPU\fP"
.br
.RI "Processzor\&. "
.ti -1c
.RI "class \fBGPU\fP"
.br
.RI "Videókártya\&. "
.ti -1c
.RI "class \fBMOBO\fP"
.br
.RI "Alaplap\&. "
.ti -1c
.RI "class \fBRAM\fP"
.br
.RI "Memória\&. "
.ti -1c
.RI "class \fBCase\fP"
.br
.RI "Ház\&. "
.ti -1c
.RI "class \fBPSU\fP"
.br
.RI "Táp\&. "
.ti -1c
.RI "class \fBStorage\fP"
.br
.RI "Tárhely alap\&. "
.ti -1c
.RI "class \fBSSD\fP"
.br
.RI "\fBSSD\fP\&. "
.ti -1c
.RI "class \fBHDD\fP"
.br
.RI "Merevlemez\&. "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (std::ostream &, const \fBPart\fP &)"
.br
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (\fButos_ostream\fP, const \fBPart\fP &)"
.br
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (std::ostream &, const \fBCPU\fP &)"
.br
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (\fButos_ostream\fP, const \fBCPU\fP &)"
.br
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (std::ostream &, const \fBGPU\fP &)"
.br
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (\fButos_ostream\fP, const \fBGPU\fP &)"
.br
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (std::ostream &, const \fBMOBO\fP &)"
.br
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (\fButos_ostream\fP, const \fBMOBO\fP &)"
.br
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (std::ostream &, const \fBRAM\fP &)"
.br
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (\fButos_ostream\fP, const \fBRAM\fP &)"
.br
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (std::ostream &, const \fBCase\fP &)"
.br
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (\fButos_ostream\fP, const \fBCase\fP &)"
.br
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (std::ostream &, const \fBPSU\fP &)"
.br
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (\fButos_ostream\fP, const \fBPSU\fP &)"
.br
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (std::ostream &, const \fBStorage\fP &)"
.br
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (\fButos_ostream\fP, const \fBStorage\fP &)"
.br
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (std::ostream &, const \fBSSD\fP &)"
.br
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (\fButos_ostream\fP, const \fBSSD\fP &)"
.br
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (std::ostream &, const \fBHDD\fP &)"
.br
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (\fButos_ostream\fP, const \fBHDD\fP &)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "std::ostream& operator<< (std::ostream &, const \fBPart\fP &)"

.SS "std::ostream& operator<< (\fButos_ostream\fP, const \fBPart\fP &)"

.SS "std::ostream& operator<< (std::ostream &, const \fBCPU\fP &)"

.SS "std::ostream& operator<< (\fButos_ostream\fP, const \fBCPU\fP &)"

.SS "std::ostream& operator<< (std::ostream &, const \fBGPU\fP &)"

.SS "std::ostream& operator<< (\fButos_ostream\fP, const \fBGPU\fP &)"

.SS "std::ostream& operator<< (std::ostream &, const \fBMOBO\fP &)"

.SS "std::ostream& operator<< (\fButos_ostream\fP, const \fBMOBO\fP &)"

.SS "std::ostream& operator<< (std::ostream &, const \fBRAM\fP &)"

.SS "std::ostream& operator<< (\fButos_ostream\fP, const \fBRAM\fP &)"

.SS "std::ostream& operator<< (std::ostream &, const \fBCase\fP &)"

.SS "std::ostream& operator<< (\fButos_ostream\fP, const \fBCase\fP &)"

.SS "std::ostream& operator<< (std::ostream &, const \fBPSU\fP &)"

.SS "std::ostream& operator<< (\fButos_ostream\fP, const \fBPSU\fP &)"

.SS "std::ostream& operator<< (std::ostream &, const \fBStorage\fP &)"

.SS "std::ostream& operator<< (\fButos_ostream\fP, const \fBStorage\fP &)"

.SS "std::ostream& operator<< (std::ostream &, const \fBSSD\fP &)"

.SS "std::ostream& operator<< (\fButos_ostream\fP, const \fBSSD\fP &)"

.SS "std::ostream& operator<< (std::ostream &, const \fBHDD\fP &)"

.SS "std::ostream& operator<< (\fButos_ostream\fP, const \fBHDD\fP &)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Prog2HF from the source code\&.
