.TH "C:/Users/cxl20/Documents/Visual Studio 2017/Prog2HF/Prog2HF/Parts.h" 3 "Wed Apr 3 2019" "Prog2HF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/cxl20/Documents/Visual Studio 2017/Prog2HF/Prog2HF/Parts.h
.SH SYNOPSIS
.br
.PP
\fC#include 'schtring\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPart\fP"
.br
.ti -1c
.RI "class \fBCPU\fP"
.br
.ti -1c
.RI "class \fBGPU\fP"
.br
.ti -1c
.RI "class \fBMOBO\fP"
.br
.ti -1c
.RI "class \fBRAM\fP"
.br
.ti -1c
.RI "class \fBCase\fP"
.br
.ti -1c
.RI "class \fBPSU\fP"
.br
.ti -1c
.RI "class \fBStorage\fP"
.br
.ti -1c
.RI "class \fBSSD\fP"
.br
.ti -1c
.RI "class \fBHDD\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Prog2HF from the source code\&.
