.TH "C:/Users/cxl20/Documents/Visual Studio 2017/Prog2HF/Prog2HF/Parts.cpp" 3 "Wed Apr 3 2019" "Prog2HF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/cxl20/Documents/Visual Studio 2017/Prog2HF/Prog2HF/Parts.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'Parts\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Prog2HF from the source code\&.
