.TH "Part" 3 "Wed Apr 3 2019" "Prog2HF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Part
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Parts\&.h>\fP
.PP
Inherited by \fBCase\fP, \fBCPU\fP, \fBGPU\fP, \fBMOBO\fP, \fBPSU\fP, \fBRAM\fP, and \fBStorage\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPart\fP (\fBString\fP \fBbrand\fP, \fBString\fP \fBtype\fP, int \fBprice\fP)"
.br
.RI "Ár\&. "
.ti -1c
.RI "virtual \fB~Part\fP ()"
.br
.ti -1c
.RI "\fBString\fP \fBget_gyarto\fP (\fBPart\fP a)"
.br
.ti -1c
.RI "\fBString\fP \fBget_nev\fP (\fBPart\fP a)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBString\fP \fBbrand\fP"
.br
.ti -1c
.RI "\fBString\fP \fBtype\fP"
.br
.RI "Gyártó "
.ti -1c
.RI "int \fBprice\fP"
.br
.RI "Típus\&. "
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Part::Part (\fBString\fP brand, \fBString\fP type, int price)\fC [inline]\fP, \fC [explicit]\fP"

.PP
Ár\&. 
.SS "virtual Part::~Part ()\fC [inline]\fP, \fC [virtual]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBString\fP Part::get_gyarto (\fBPart\fP a)\fC [inline]\fP"

.SS "\fBString\fP Part::get_nev (\fBPart\fP a)\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBString\fP Part::brand\fC [protected]\fP"

.SS "int Part::price\fC [protected]\fP"

.PP
Típus\&. 
.SS "\fBString\fP Part::type\fC [protected]\fP"

.PP
Gyártó 

.SH "Author"
.PP 
Generated automatically by Doxygen for Prog2HF from the source code\&.
