.TH "C:/Users/cxl20/Documents/Visual Studio 2017/Prog2HF/Prog2HF/Parts.cpp" 3 "Fri May 3 2019" "Prog2HF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/cxl20/Documents/Visual Studio 2017/Prog2HF/Prog2HF/Parts.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'Parts\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (std::ostream &os, const \fBPart\fP &p)"
.br
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (\fButos_ostream\fP tos, const \fBPart\fP &p)"
.br
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (std::ostream &os, const \fBCPU\fP &p)"
.br
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (\fButos_ostream\fP tos, const \fBCPU\fP &p)"
.br
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (std::ostream &os, const \fBGPU\fP &p)"
.br
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (\fButos_ostream\fP tos, const \fBGPU\fP &p)"
.br
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (std::ostream &os, const \fBMOBO\fP &p)"
.br
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (\fButos_ostream\fP tos, const \fBMOBO\fP &p)"
.br
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (std::ostream &os, const \fBRAM\fP &p)"
.br
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (\fButos_ostream\fP tos, const \fBRAM\fP &p)"
.br
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (std::ostream &os, const \fBCase\fP &p)"
.br
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (\fButos_ostream\fP tos, const \fBCase\fP &p)"
.br
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (std::ostream &os, const \fBPSU\fP &p)"
.br
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (\fButos_ostream\fP tos, const \fBPSU\fP &p)"
.br
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (std::ostream &os, const \fBStorage\fP &p)"
.br
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (\fButos_ostream\fP tos, const \fBStorage\fP &p)"
.br
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (std::ostream &os, const \fBSSD\fP &p)"
.br
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (\fButos_ostream\fP tos, const \fBSSD\fP &p)"
.br
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (std::ostream &os, const \fBHDD\fP &p)"
.br
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (\fButos_ostream\fP tos, const \fBHDD\fP &p)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "std::ostream& operator<< (std::ostream & os, const \fBPart\fP & p)"

.SS "std::ostream& operator<< (\fButos_ostream\fP tos, const \fBPart\fP & p)"

.SS "std::ostream& operator<< (std::ostream & os, const \fBCPU\fP & p)"

.SS "std::ostream& operator<< (\fButos_ostream\fP tos, const \fBCPU\fP & p)"

.SS "std::ostream& operator<< (std::ostream & os, const \fBGPU\fP & p)"

.SS "std::ostream& operator<< (\fButos_ostream\fP tos, const \fBGPU\fP & p)"

.SS "std::ostream& operator<< (std::ostream & os, const \fBMOBO\fP & p)"

.SS "std::ostream& operator<< (\fButos_ostream\fP tos, const \fBMOBO\fP & p)"

.SS "std::ostream& operator<< (std::ostream & os, const \fBRAM\fP & p)"

.SS "std::ostream& operator<< (\fButos_ostream\fP tos, const \fBRAM\fP & p)"

.SS "std::ostream& operator<< (std::ostream & os, const \fBCase\fP & p)"

.SS "std::ostream& operator<< (\fButos_ostream\fP tos, const \fBCase\fP & p)"

.SS "std::ostream& operator<< (std::ostream & os, const \fBPSU\fP & p)"

.SS "std::ostream& operator<< (\fButos_ostream\fP tos, const \fBPSU\fP & p)"

.SS "std::ostream& operator<< (std::ostream & os, const \fBStorage\fP & p)"

.SS "std::ostream& operator<< (\fButos_ostream\fP tos, const \fBStorage\fP & p)"

.SS "std::ostream& operator<< (std::ostream & os, const \fBSSD\fP & p)"

.SS "std::ostream& operator<< (\fButos_ostream\fP tos, const \fBSSD\fP & p)"

.SS "std::ostream& operator<< (std::ostream & os, const \fBHDD\fP & p)"

.SS "std::ostream& operator<< (\fButos_ostream\fP tos, const \fBHDD\fP & p)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Prog2HF from the source code\&.
