.TH "PSU" 3 "Wed Apr 3 2019" "Prog2HF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PSU
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Parts\&.h>\fP
.PP
Inherits \fBPart\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPSU\fP (\fBString\fP \fBbrand\fP, \fBString\fP \fBtype\fP, int \fBprice\fP, \fBString\fP wattage)"
.br
.RI "Teljesítmény\&. "
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "PSU::PSU (\fBString\fP brand, \fBString\fP type, int price, \fBString\fP wattage)\fC [inline]\fP, \fC [explicit]\fP"

.PP
Teljesítmény\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Prog2HF from the source code\&.
