.TH "RAM" 3 "Fri May 3 2019" "Prog2HF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RAM \- Memória\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Parts\&.h>\fP
.PP
Inherits \fBPart\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRAM\fP (\fBString\fP \fBbrand\fP, \fBString\fP \fBtype\fP, int \fBprice\fP, int clk, int size)"
.br
.ti -1c
.RI "\fBRAM\fP (\fBTempInput\fP tmp)"
.br
.ti -1c
.RI "void \fBprint\fP (std::ostream &os) const"
.br
.ti -1c
.RI "void \fBprint\fP (\fButos_ostream\fP &tos) const"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Memória\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "RAM::RAM (\fBString\fP brand, \fBString\fP type, int price, int clk, int size)\fC [inline]\fP, \fC [explicit]\fP"

.SS "RAM::RAM (\fBTempInput\fP tmp)\fC [inline]\fP, \fC [explicit]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void RAM::print (std::ostream & os) const\fC [virtual]\fP"

.PP
Reimplemented from \fBPart\fP\&.
.SS "void RAM::print (\fButos_ostream\fP & tos) const\fC [virtual]\fP"

.PP
Reimplemented from \fBPart\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Prog2HF from the source code\&.
