.TH "C:/Users/cxl20/Documents/Visual Studio 2017/Prog2HF/Prog2HF/schtring.h" 3 "Wed Apr 3 2019" "Prog2HF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/cxl20/Documents/Visual Studio 2017/Prog2HF/Prog2HF/schtring.h
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <cstring>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBString\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (std::ostream &os, const \fBString\fP &s0)"
.br
.RI "inserter operator "
.ti -1c
.RI "std::istream & \fBoperator>>\fP (std::istream &is, \fBString\fP &s0)"
.br
.RI "extractor operator "
.ti -1c
.RI "\fBString\fP \fBoperator+\fP (char ch, const \fBString\fP &str)"
.br
.RI "karakter + string "
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBString\fP operator+ (char ch, const \fBString\fP & str)\fC [inline]\fP"

.PP
karakter + string 
.SS "std::ostream& operator<< (std::ostream & os, const \fBString\fP & s0)"

.PP
inserter operator 
.SS "std::istream& operator>> (std::istream & is, \fBString\fP & s0)"

.PP
extractor operator 
.SH "Author"
.PP 
Generated automatically by Doxygen for Prog2HF from the source code\&.
