.TH "C:/Users/cxl20/Documents/Visual Studio 2017/Prog2HF/Prog2HF/schtring.hpp" 3 "Thu May 2 2019" "Prog2HF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/cxl20/Documents/Visual Studio 2017/Prog2HF/Prog2HF/schtring.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <cstring>\fP
.br
\fC#include <ctype\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fButos_t\fP"
.br
.RI "szóközösítő toggle "
.ti -1c
.RI "struct \fButos_ostream\fP"
.br
.RI "szóközösítő stream manipulator "
.ti -1c
.RI "class \fBString\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fButos_ostream\fP \fBoperator<<\fP (std::ostream &os, \fButos_t\fP)"
.br
.RI "szóközösítő stream manipulator "
.ti -1c
.RI "template<typename T > std::ostream & \fBoperator<<\fP (\fButos_ostream\fP tos, const T &v)"
.br
.RI "szóközösítő ostream "
.ti -1c
.RI "char * \fBstolower\fP (char *s)"
.br
.RI "char tömb kisbetűsítése "
.ti -1c
.RI "\fBString\fP \fBoperator+\fP (char ch, const \fBString\fP &str)"
.br
.RI "karakter + string "
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (std::ostream &os, const \fBString\fP &s0)"
.br
.RI "inserter operator "
.ti -1c
.RI "std::istream & \fBoperator>>\fP (std::istream &is, \fBString\fP &s0)"
.br
.RI "extractor operator "
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (\fButos_ostream\fP tos, const \fBString\fP &s0)"
.br
.RI "alsóvonást szóközzé alakító kiírás "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "constexpr \fButos_t\fP \fButos\fP"
.br
.RI "szóközösítő toggle "
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBString\fP operator+ (char ch, const \fBString\fP & str)\fC [inline]\fP"

.PP
karakter + string 
.SS "\fButos_ostream\fP operator<< (std::ostream & os, \fButos_t\fP)\fC [inline]\fP"

.PP
szóközösítő stream manipulator 
.SS "template<typename T > std::ostream& operator<< (\fButos_ostream\fP tos, const T & v)"

.PP
szóközösítő ostream 
.SS "std::ostream& operator<< (std::ostream & os, const \fBString\fP & s0)"

.PP
inserter operator 
.SS "std::ostream& operator<< (\fButos_ostream\fP tos, const \fBString\fP & s0)"

.PP
alsóvonást szóközzé alakító kiírás 
.SS "std::istream& operator>> (std::istream & is, \fBString\fP & s0)"

.PP
extractor operator 
.SS "char* stolower (char * s)"

.PP
char tömb kisbetűsítése 
.SH "Variable Documentation"
.PP 
.SS "constexpr \fButos_t\fP utos"

.PP
szóközösítő toggle 
.SH "Author"
.PP 
Generated automatically by Doxygen for Prog2HF from the source code\&.
