.TH "Storage" 3 "Fri May 3 2019" "Prog2HF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Storage \- Tárhely alap\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Parts\&.h>\fP
.PP
Inherits \fBPart\fP\&.
.PP
Inherited by \fBHDD\fP, and \fBSSD\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBStorage\fP (\fBString\fP \fBbrand\fP, \fBString\fP \fBtype\fP, int \fBprice\fP, int \fBsize\fP, int \fBreadspeed\fP, int \fBwritespeed\fP)"
.br
.ti -1c
.RI "virtual void \fBprint\fP (std::ostream &os) const"
.br
.ti -1c
.RI "virtual void \fBprint\fP (\fButos_ostream\fP &tos) const"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "int \fBsize\fP"
.br
.RI "Méret\&. "
.ti -1c
.RI "int \fBreadspeed\fP"
.br
.RI "Olvasási sebesség\&. "
.ti -1c
.RI "int \fBwritespeed\fP"
.br
.RI "Írási sebesség\&. "
.in -1c
.SH "Detailed Description"
.PP 
Tárhely alap\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Storage::Storage (\fBString\fP brand, \fBString\fP type, int price, int size, int readspeed, int writespeed)\fC [inline]\fP, \fC [explicit]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void Storage::print (std::ostream & os) const\fC [virtual]\fP"

.PP
Reimplemented from \fBPart\fP\&.
.PP
Reimplemented in \fBHDD\fP, and \fBSSD\fP\&.
.SS "void Storage::print (\fButos_ostream\fP & tos) const\fC [virtual]\fP"

.PP
Reimplemented from \fBPart\fP\&.
.PP
Reimplemented in \fBHDD\fP, and \fBSSD\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "int Storage::readspeed\fC [protected]\fP"

.PP
Olvasási sebesség\&. 
.SS "int Storage::size\fC [protected]\fP"

.PP
Méret\&. 
.SS "int Storage::writespeed\fC [protected]\fP"

.PP
Írási sebesség\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Prog2HF from the source code\&.
