.TH "C:/Users/cxl20/Documents/Visual Studio 2017/Prog2HF/Prog2HF/schtring/string5.h" 3 "Tue Apr 2 2019" "Prog2HF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/cxl20/Documents/Visual Studio 2017/Prog2HF/Prog2HF/schtring/string5.h
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBString\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (std::ostream &os, const \fBString\fP &s0)"
.br
.ti -1c
.RI "std::istream & \fBoperator>>\fP (std::istream &is, \fBString\fP &s0)"
.br
.ti -1c
.RI "\fBString\fP \fBoperator+\fP (char ch, const \fBString\fP &str)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBString\fP operator+ (char ch, const \fBString\fP & str)\fC [inline]\fP"

.SS "std::ostream& operator<< (std::ostream & os, const \fBString\fP & s0)"

.SS "std::istream& operator>> (std::istream & is, \fBString\fP & s0)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Prog2HF from the source code\&.
