.TH "TempInput" 3 "Fri May 3 2019" "Prog2HF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TempInput \- Lehetséges inputokat tárolja adatokkal való konstruáláshoz\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Parts\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBString\fP \fBinstruction\fP"
.br
.RI "Mihez tartozik a változó "
.ti -1c
.RI "\fBString\fP \fBclname\fP"
.br
.RI "Kompatibilitás lista neve\&. "
.ti -1c
.RI "\fBString\fP \fBbrand\fP"
.br
.RI "Gyártó "
.ti -1c
.RI "\fBString\fP \fBtype\fP"
.br
.RI "Típus\&. "
.ti -1c
.RI "int \fBprice\fP"
.br
.RI "Ár\&. "
.ti -1c
.RI "\fBString\fP \fBsocket\fP"
.br
.RI "Foglalat\&. "
.ti -1c
.RI "int \fBclk\fP"
.br
.RI "Órajel\&. "
.ti -1c
.RI "int \fBcores\fP"
.br
.RI "Magok száma\&. "
.ti -1c
.RI "bool \fBmultithreading\fP"
.br
.RI "Multithreading support\&. "
.ti -1c
.RI "\fBString\fP \fBchipset\fP"
.br
.RI "Chipset\&. "
.ti -1c
.RI "\fBString\fP \fBformfactor\fP"
.br
.RI "Méret szabvány\&. "
.ti -1c
.RI "int \fBsize\fP"
.br
.RI "Memória méret\&. "
.ti -1c
.RI "int \fBwattage\fP"
.br
.RI "Teljesítmény\&. "
.ti -1c
.RI "int \fBreadspeed\fP"
.br
.RI "Olvasási sebesség\&. "
.ti -1c
.RI "int \fBwritespeed\fP"
.br
.RI "Írási sebesség\&. "
.ti -1c
.RI "\fBString\fP \fBflashtype\fP"
.br
.RI "Flash csip típusa\&. "
.ti -1c
.RI "int \fBrpm\fP"
.br
.RI "Fordulatszám\&. "
.in -1c
.SH "Detailed Description"
.PP 
Lehetséges inputokat tárolja adatokkal való konstruáláshoz\&. 
.SH "Member Data Documentation"
.PP 
.SS "\fBString\fP TempInput::brand"

.PP
Gyártó 
.SS "\fBString\fP TempInput::chipset"

.PP
Chipset\&. 
.SS "int TempInput::clk"

.PP
Órajel\&. 
.SS "\fBString\fP TempInput::clname"

.PP
Kompatibilitás lista neve\&. 
.SS "int TempInput::cores"

.PP
Magok száma\&. 
.SS "\fBString\fP TempInput::flashtype"

.PP
Flash csip típusa\&. 
.SS "\fBString\fP TempInput::formfactor"

.PP
Méret szabvány\&. 
.SS "\fBString\fP TempInput::instruction"

.PP
Mihez tartozik a változó 
.SS "bool TempInput::multithreading"

.PP
Multithreading support\&. 
.SS "int TempInput::price"

.PP
Ár\&. 
.SS "int TempInput::readspeed"

.PP
Olvasási sebesség\&. 
.SS "int TempInput::rpm"

.PP
Fordulatszám\&. 
.SS "int TempInput::size"

.PP
Memória méret\&. 
.SS "\fBString\fP TempInput::socket"

.PP
Foglalat\&. 
.SS "\fBString\fP TempInput::type"

.PP
Típus\&. 
.SS "int TempInput::wattage"

.PP
Teljesítmény\&. 
.SS "int TempInput::writespeed"

.PP
Írási sebesség\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Prog2HF from the source code\&.
