.TH "utos_t" 3 "Fri May 3 2019" "Prog2HF" \" -*- nroff -*-
.ad l
.nh
.SH NAME
utos_t \- szóközösítő toggle  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <schtring\&.hpp>\fP
.SH "Detailed Description"
.PP 
szóközösítő toggle 

.SH "Author"
.PP 
Generated automatically by Doxygen for Prog2HF from the source code\&.
